name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Change to project directory
        run: cd Onlypics
        # Replace "/ruta/a/tu/proyecto" with the actual path to your project.

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Check project directory
        run: ls Onlypics
        # Replace "/ruta/a/tu/proyecto" with the actual path to your project.

      # Your existing Cypress run step
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start